### ISSUE TITLE
[Roadmap] Version 0.1 Release

### ISSUE THREAD

**Issue by skim0119** [skim0119/gym-softrobot#1]
## Version 0.1 - Alpha

The issue keeps track of the TODO/FIXME list and the progress report.

### Environment

- [x] Tune and complete the structure `OctoFlat-v0`
  - [x] Reconsider the joint between octopus body and the arm.
  - [x] Include pyglet
  - [x] Include vaprory
  - [x] Test vapory rendering on pyglet
  - [x] Add rendering in OctoFlat
  - [x] #4
- [x] Complete and trial training for 'ContinuumSnake-v0`
  - [x] Add rendering
- [x] Reward and other training detail logging.
- [x] <s>Finish `OctoReach`</s> Will be done in next version.

### Visualization Utility

- [x] Link povray to pyglet
- [x] Matplotlib plots
- [x] Save data

### Repository

- [x] Update readme
  - [x] Environment description
- [x] Debuggin scripts
  - [x] make
  - [x] render
  - [x] registry
